server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://psql-test.csduuw1qv06o.us-west-2.rds.amazonaws.com:5432/base
    username: psql
    password: null
  jpa:
    hibernate:
      ddl-auto: update